# Generated by Django 5.1.3 on 2024-11-30 10:53

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('interested_in', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=40)),
                ('beginning_teaching', models.DateField()),
                ('teaching_subject_1', models.CharField(default='', max_length=100)),
                ('teaching_subject_2', models.CharField(default='', max_length=100)),
                ('teaching_subject_3', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time_scheduled', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('charge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('students', models.ManyToManyField(to='seminars.student')),
                ('teachers', models.ManyToManyField(to='seminars.teacher')),
            ],
        ),
    ]
