# Generated by Django 5.1.3 on 2024-12-07 19:25

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='awd',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('age'), '*', models.Value(2)), output_field=models.DecimalField(decimal_places=2, max_digits=4)),
        ),
    ]
